// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LearningSystemAPI.DatabaseFirst;

public partial class Presentations
{
    [Key]
    public Guid Id { get; set; }

    public string Label { get; set; }

    public string Summary { get; set; }

    [Required]
    public byte[] FileData { get; set; }

    [Required]
    [StringLength(255)]
    public string FileName { get; set; }

    [Required]
    [StringLength(100)]
    public string ContentType { get; set; }

    public Guid? SubjectId { get; set; }

    [ForeignKey("SubjectId")]
    [InverseProperty("Presentations")]
    public virtual Subject Subject { get; set; }
}