// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LearningSystemAPI.DatabaseFirst;

public partial class Subject
{
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Semester { get; set; }

    public int Year { get; set; }

    [Key]
    public Guid Id { get; set; }

    [InverseProperty("Subject")]
    public virtual ICollection<Presentations> Presentations { get; set; } = new List<Presentations>();
}